### ISSUE TITLE
Multi container stats

### ISSUE THREAD

**Issue by jtclint** [bobrik/collectd-docker#18]
Option to monitor all containers on a specific host, maybe this already exist and I do not understand your documentation.  If so please let me know and I will test.  I may also be able to get some help in adding this feature as well if it does not exist, if so I will let you know.

Possibly this would work by setting the COLLECTD_DOCKER_APP="*" or something similar.

Thanks

**Comment by bobrik** [comment]
You can only monitor containers with `COLLECTD_DOCKER_APP` set to something. So the easiest way of monitoring all containers is to set this variable everywhere. If app name is not set on a docker container, it cannot be monitored.

Can you explain why you want to monitor all containers, but cannot set env variable everywhere?

**Comment by sherzberg** [comment]
I actually would like this feature too. Right now, I'm going through all of our apps json for marathon and having to add this. But it would have been nice to just say, monitor everything with no changes to our current deployment setup.

We use mesos and the docker executer for everything (we are adding more and more running containers ever day) and it would be nice to just tell collectd-docker to just monitor everything.

**Comment by bobrik** [comment]
@sherzberg isn't your problem solved with #19?

**Comment by sherzberg** [comment]
Yes, for marathon based apps. Unfortunately we have a few non-marathon docker containers deployed so we can't rely on `MARATHON_APP_ID` being set all the time. So I think this issue is still a good one to implement.

**Comment by bobrik** [comment]
If we monitor everything, where do we get app name? Do we just take container name?

**Comment by sherzberg** [comment]
That might work, the only issue is that it is random. Maybe the image name? It could even be `full_image_name.tag` which would be helpful to see metric differences between tags.

**Comment by bobrik** [comment]
Why would it be random? How do you run your containers?

Image and are not unique, it's common to have many containers from the same image on one host.

**Comment by sherzberg** [comment]
The container name is randomly generated:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
0b3e1f06302b        alpine              "sleep 1000"        2 seconds ago       Up 2 seconds                            boring_colden
d7984b865273        alpine              "sleep 1000"        7 seconds ago       Up 7 seconds                            happy_brattain
```

I guess we always build a new docker image for everything that is run in our environment, so I guess the image name wouldn't be unique. We just never run the same image with different commands.

**Comment by sherzberg** [comment]
So I guess I am not sure what the best place to get the name from would be.

**Comment by bobrik** [comment]
Can you set container name in your env? Can you set env variable to use what works right now?

**Comment by sherzberg** [comment]
I am fine with that. 99% of our containers run in marathon anyway. Thanks for talking through this though.

**Comment by xneo64** [comment]
@bobrik Would you consider adding the option to enable reading the container name and use that as label?
I maintain a large-ish graphite setup as part of an Ops team, and all of our applications implement a fixed container name. It would be difficult for us to manually label / orchestrate your container on hosts running multiple containers. It would be equally impractical to get the dev teams to modify their container images to include labels for us to use :)

I believe that adding this option would enable people deploying their containers with a fixed name, to easily implement your monitoring container with minimal further intervention/setup.

**Comment by bobrik** [comment]
@xneo64 I can review a PR if you want to do it.
